/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Units;

import Data.Configuration.StringsKeysHelper;
import Data.Dao.Interfaces.IMeasurementUnitRepository;
import Data.Entities.MeasurementUnit;
import General.JInternalFrameCenter;
import javax.swing.JOptionPane;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author GlobalDev
 */
public class AddEditUnits extends JInternalFrameCenter {

    /**
     * Creates new form AddEditUnits
     */
    IMeasurementUnitRepository _measurementUnitRepository;
    MeasurementUnit _mu;
    Boolean flagEdit=false;
        
    public AddEditUnits() {
        initComponents();        
        ClassPathXmlApplicationContext ctx=  new ClassPathXmlApplicationContext(StringsKeysHelper.applicationContextFile);
        _measurementUnitRepository = (IMeasurementUnitRepository)ctx.getBean(StringsKeysHelper.MeasurementeUnitRepository);        
    }
    
    public AddEditUnits(MeasurementUnit mu)
    {
        this();
        _mu=mu;
        if(_mu!=null)
        {
            this.txt_description.setText(_mu.getDescription());
            this.txt_abbreviation.setText(_mu.getAbbreviation());
            this.btn_ok.setText("Actualizar");
            flagEdit=true;
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "No se pudo cargar la informacion de la Unidad, favor reintente.");
            this.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_abbreviation = new javax.swing.JTextField();
        btn_exit = new javax.swing.JButton();

        setClosable(true);
        setTitle("Agregar/Modificar Unidades");

        btn_ok.setText("Aceptar");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jLabel1.setText("Descripcion:");

        jLabel2.setText("Abreviacion:");

        btn_exit.setText("Salir");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_exit))
                    .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_abbreviation, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_abbreviation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok)
                    .addComponent(btn_exit))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        if(flagEdit)
        {
            _mu.setDescription(this.txt_description.getText());
            _mu.setAbbreviation(this.txt_abbreviation.getText());
            if(_measurementUnitRepository.UpdateUnit(_mu))
                JOptionPane.showMessageDialog(rootPane, "Unidad modificada exitosamente.");
            else
                JOptionPane.showMessageDialog(rootPane, "Hubo un error mientras se modificaba la unidad.");            
        }
        else
        {
            if(_measurementUnitRepository.CreateNewUnit(this.txt_description.getText(), this.txt_abbreviation.getText()))
                JOptionPane.showMessageDialog(rootPane,"Unidad creada exitosamente");
            else
                JOptionPane.showMessageDialog(rootPane,"Hubo un error mientras se creaba la unidad, favor reintente o contacte con el administrador del sistema");
        } 
        this.dispose();
    }//GEN-LAST:event_btn_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_abbreviation;
    private javax.swing.JTextField txt_description;
    // End of variables declaration//GEN-END:variables
}
