/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Units;

import Data.Configuration.StringsKeysHelper;
import Data.Dao.Interfaces.IMeasurementUnitRepository;
import Data.Entities.MeasurementUnit;
import General.JInternalFrameCenter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author GlobalDev
 */
public class ListUnits extends JInternalFrameCenter{
    DefaultTableModel dtm;
    IMeasurementUnitRepository _measurementUnitRepository;    
    /**
     * Creates new form ListUnits
     */
    public ListUnits() {
        initComponents();
        ClassPathXmlApplicationContext ctx = new ClassPathXmlApplicationContext(StringsKeysHelper.applicationContextFile);
        _measurementUnitRepository =(IMeasurementUnitRepository) ctx.getBean(StringsKeysHelper.MeasurementeUnitRepository);
        dtm = new DefaultTableModel();
        dtm.addColumn("Descripcion");
        dtm.addColumn("Abreviacion");  
        dtm.addColumn("");        
    }

    
    private void fillTableUnits(List<MeasurementUnit> units,DefaultTableModel model)    
    {        
        model.setRowCount(0);
        this.tbl_Units.setModel(model);             
        this.tbl_Units.getColumnModel().getColumn(2).setMinWidth(0);
        this.tbl_Units.getColumnModel().getColumn(2).setMaxWidth(0);
        Object [] fila = new Object[3];
        for(MeasurementUnit p:units)
        {
           fila[0]=p.getDescription();
           fila[1] = p.getAbbreviation(); 
           fila[2] = p.getId();           
           model.addRow(fila);
        }     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Units = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_list = new javax.swing.JButton();
        btn_modify = new javax.swing.JButton();
        lb_totalUnits = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();

        setClosable(true);
        setTitle("Modulo Unidades de Medida");

        Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tbl_Units.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_Units.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_UnitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Units);

        btn_search.setText("Buscar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_list.setText("Listar");
        btn_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listActionPerformed(evt);
            }
        });

        btn_modify.setText("Modificar");
        btn_modify.setEnabled(false);
        btn_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyActionPerformed(evt);
            }
        });

        lb_totalUnits.setText("Total Unidades:");

        btn_add.setText("Agregar");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_search))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(btn_list, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_totalUnits)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_list)
                    .addComponent(btn_modify)
                    .addComponent(lb_totalUnits)
                    .addComponent(btn_add))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listActionPerformed
        List<MeasurementUnit> units = _measurementUnitRepository.GetAll();
        this.fillTableUnits(units, dtm);
        this.lb_totalUnits.setText("Total Unidades: "+ units.size());
    }//GEN-LAST:event_btn_listActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        AddEditUnits Aeu= new AddEditUnits();
        this.getParent().add(Aeu);
        this.dispose();
        Aeu.Centrar();
        Aeu.show();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        this.fillTableUnits(_measurementUnitRepository.FindByDescription(this.txt_search.getText()), dtm);
         this.lb_totalUnits.setText("Total Unidades: "+ dtm.getRowCount());
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyActionPerformed
        AddEditUnits aeu = new AddEditUnits(_measurementUnitRepository.Get(unitId));        
        this.getParent().add(aeu);
        this.dispose();
        aeu.Centrar();
        aeu.show();
    }//GEN-LAST:event_btn_modifyActionPerformed
    int unitId=0;
    private void tbl_UnitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_UnitsMouseClicked
        unitId =(int) this.tbl_Units.getValueAt(this.tbl_Units.getSelectedRow(),2);        
        if(unitId>0)
            this.btn_modify.setEnabled(true);
        else
            this.btn_modify.setEnabled(false);
    }//GEN-LAST:event_tbl_UnitsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_list;
    private javax.swing.JButton btn_modify;
    private javax.swing.JButton btn_search;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_totalUnits;
    private javax.swing.JTable tbl_Units;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
