/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedor;

import Data.Configuration.StringsKeysHelper;
import Data.Dao.Interfaces.IProveedorRepository;
import Data.Entities.Proveedor;
import General.JInternalFrameCenter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author GlobalDev
 */
public class ListarProveedores extends JInternalFrameCenter {

    /**
     * Creates new form ListarProveedores
     */
    IProveedorRepository _proveedorRepository;
    DefaultTableModel dtm;
    public ListarProveedores() {
        initComponents();  
        ClassPathXmlApplicationContext ctx = new ClassPathXmlApplicationContext(StringsKeysHelper.applicationContextFile);
        _proveedorRepository = (IProveedorRepository) ctx.getBean(StringsKeysHelper.ProveedorRepository);
        dtm = new DefaultTableModel();
        dtm.addColumn("Id");
        dtm.addColumn("Nombre");
        dtm.addColumn("Estado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProveedoresTable = new javax.swing.JTable();
        btn_listActives = new javax.swing.JButton();
        txt_nombreProv = new javax.swing.JTextField();
        bnt_filtrar = new javax.swing.JButton();

        setClosable(true);

        ProveedoresTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(ProveedoresTable);

        btn_listActives.setText("Listar Activos");
        btn_listActives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listActivesActionPerformed(evt);
            }
        });

        bnt_filtrar.setText("Buscar");
        bnt_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_filtrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_nombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bnt_filtrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_listActives)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt_filtrar))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_listActives))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_listActivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listActivesActionPerformed
        List<Proveedor> list = _proveedorRepository.GetAllActives();
        this.fillTableProveedor(list, dtm);        
    }//GEN-LAST:event_btn_listActivesActionPerformed

    private void bnt_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_filtrarActionPerformed
        List<Proveedor> list = _proveedorRepository.FindByName(this.txt_nombreProv.getText());
        this.fillTableProveedor(list, dtm);
    }//GEN-LAST:event_bnt_filtrarActionPerformed

    private void fillTableProveedor(List<Proveedor> proveedores,DefaultTableModel model)    
    {        
        model.setRowCount(0);
        this.ProveedoresTable.setModel(model);             
        Object [] fila = new Object[3];
        for(Proveedor p:proveedores)
        {
           fila[0]=p.getId();
           fila[1] = p.getNombre();
           fila[2] = p.getActive()==1 ? "Activo":"Inactivo"; 
           model.addRow(fila);
        }     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProveedoresTable;
    private javax.swing.JButton bnt_filtrar;
    private javax.swing.JButton btn_listActives;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_nombreProv;
    // End of variables declaration//GEN-END:variables
}
